language: node_js
node_js:
- stable
script:
- npm run build
after_success:
- ".travis/push.sh"
env:
  global:
    secure: QTcVY7HY+sThvQxgdMgw9oU5VqqJMt2vtq5G3PVygeiVAbdKDIgoaX1A2Seh/dHU9V632iKGfTy3Rnm4Cuh2Ymtue+f09/GCj5dE1vIvlZVPno7uTlFsG2Om9r4bcBThEfzBMdVaRemxrVm1cHSmEfHgBRR4CeX5eWuC8yNyy3sdcS3rXVb+VMEnT+mLbDI1zqmW1l1Qc2cIWlX3koxw+FGS2+lAlrl2vjoJ+yBKuXk4QiN3xCHiYBuWQJIgD6zR76c05Ip08w9P19qYMWjl3n/6j6Jl7ZkIuqigoDmFbfRx5IyZUCT/5XnPDZeRNduxkETnyFcqXLFv5knuJYXXQRyA+IYbJwT1tJTRKXcnAuPolkxSjZOTRocVxoxGyjEM5GqIq8V/Cvne8cPGUkRuCHHoyByWI+//Q/cNCiSBTxYW/e6s6HSlv9BSWDcZTnB0LuDntPaGyn3CNvx+AylI2ShKxpSxYJSVHL3sqV7od3aOZDLoHf+P2YJIuv1+d527G9S7AEYGRviqDTKNDO9oxU0xBWNxViTef/eSY20Hdypl6sLLGm74mzIoMYLIyDHU594kBiIPbnq/SVkevc/A6IwAba6Kf7DqOtpuiMDbOAsfCR+aU1hsAJiVDqDNlD4EoiEj26OSbcSW40c0CcIuYKsA+W/OdvWhvEFvZb51b7c=
