language: node_js
node_js:
- stable
script:
- npm test
- npm run build
after_success:
- ".travis/push.sh"
branches:
  only:
  - develop
env:
  global:
  - secure: QTcVY7HY+sThvQxgdMgw9oU5VqqJMt2vtq5G3PVygeiVAbdKDIgoaX1A2Seh/dHU9V632iKGfTy3Rnm4Cuh2Ymtue+f09/GCj5dE1vIvlZVPno7uTlFsG2Om9r4bcBThEfzBMdVaRemxrVm1cHSmEfHgBRR4CeX5eWuC8yNyy3sdcS3rXVb+VMEnT+mLbDI1zqmW1l1Qc2cIWlX3koxw+FGS2+lAlrl2vjoJ+yBKuXk4QiN3xCHiYBuWQJIgD6zR76c05Ip08w9P19qYMWjl3n/6j6Jl7ZkIuqigoDmFbfRx5IyZUCT/5XnPDZeRNduxkETnyFcqXLFv5knuJYXXQRyA+IYbJwT1tJTRKXcnAuPolkxSjZOTRocVxoxGyjEM5GqIq8V/Cvne8cPGUkRuCHHoyByWI+//Q/cNCiSBTxYW/e6s6HSlv9BSWDcZTnB0LuDntPaGyn3CNvx+AylI2ShKxpSxYJSVHL3sqV7od3aOZDLoHf+P2YJIuv1+d527G9S7AEYGRviqDTKNDO9oxU0xBWNxViTef/eSY20Hdypl6sLLGm74mzIoMYLIyDHU594kBiIPbnq/SVkevc/A6IwAba6Kf7DqOtpuiMDbOAsfCR+aU1hsAJiVDqDNlD4EoiEj26OSbcSW40c0CcIuYKsA+W/OdvWhvEFvZb51b7c=
  - secure: mdicD5AUMXHf6ZAX+o1usHIM/W/loO3p689PkbYn/gi5ri3XCZqiE+u1wjw3UkQyuVMXF8ZgzGK6i96z1UD4Up6Cr7n/N2wIYMdbG1eJt2mEhhoZlLW10KqfwqG+WdDVUhzYxj9ieKhmD3UsBVcpVJw1cjB/9VDOxfVkNHFZJX0wGRQF6xbfUcMfkFWxmMm0N203ZUVTK+vsY5sSWpLmQ40oeCcYKaiG2wPZiAGFUxNNF8rBwSRRpy3n14R3wgkm4Y7En5iajJ9sRgYA0r4rj2iEH5QzCLWD/J3PpRfL6I4yp/hkTWjB9UYVi5YYq0hGgkFC7tkVUHKvRD/iksxkx4ZMtMwzPFrwP5+yAbiAhXk1sVmv76gNOpH1FrpqnI16MTTDev98gguOnlXM35PlXzkRDnscq/d2ckIIofJu4xvt8n5ehmW3gJADs4Av370BTTXOe7ASBfUWoWvNYLSIalv7XY1vqerBtPvwYltoDkgHqv6H/fxLCLA1HjpC9Z8Low6qBbCDS9DKj1rjcdE3bRAM+d14y/so+AmpKchw5a8ZrALizmyLqe48WXnvBtQq7X52b8CDNGW7wkndOYOJGu6EwfLmhJmzaw4yjJMMMOeI9UeLY0uMsA+BugnwiW7IxzKshRmE+jZ7OVVEP1TnAZjFzYhXlDQIyV83zLQX85c=
